name: Test Coverage Check

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    name: run tests and display coverage

    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-tests'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    env:
      SHOPIFY_FIXED_ARGS: ${{ secrets.SHOPIFY_FIXED_ARGS }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MIN_COVERAGE_THRESHOLD: '99.0'

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[milvus,shopify,hubspot]' --quiet

      - name: Run tests and check coverage threshold
        id: coverage-check
        run: |
          pytest tests/ --cov=arklex --cov-report=term-missing --cov-report=html --cov-report=xml --no-cov-on-fail

          python -c "
          import xml.etree.ElementTree as ET
          import os

          try:
              tree = ET.parse('coverage.xml')
              root = tree.getroot()
              coverage = float(root.attrib['line-rate']) * 100
              print(f'Coverage: {coverage:.1f}%')

              min_coverage = float(os.environ.get('MIN_COVERAGE_THRESHOLD', '99.0'))
              print(f'Minimum coverage threshold: {min_coverage}%')

              if coverage < min_coverage:
                  print(f'❌ Coverage ({coverage:.1f}%) is below minimum threshold ({min_coverage}%)')
                  exit(1)
              else:
                  print(f'✅ Coverage ({coverage:.1f}%) meets minimum threshold ({min_coverage}%)')

              with open(os.environ.get('GITHUB_OUTPUT', '/dev/null'), 'a') as f:
                  f.write(f'coverage={coverage:.1f}\\n')
          except Exception as e:
              print(f'Error reading coverage data: {e}')
              exit(1)
          "

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/

      - name: Display coverage comment
        id: coverage
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 99.0
          MINIMUM_ORANGE: 70

      - name: Update README badge
        run: |
          COVERAGE=${{ steps.coverage-check.outputs.coverage }}

          COLOR=$(python -c "
          coverage = float('$COVERAGE')
          if coverage < 90:
              print('red')
          elif coverage < 99:
              print('orange')
          else:
              print('green')
          ")

          sed -i "s/coverage-[0-9]\+\.[0-9]%25-[a-z]*/coverage-${COVERAGE}%25-${COLOR}/g" README.md

          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update README with ${COVERAGE}% test coverage"
            git push origin HEAD:${{ github.head_ref }}
          fi